# Generated by Django 6.1.1 on 2026-09-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
