# Generated by Django 6.1.1 on 2026-09-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_receipt_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(
                blank=True,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(
                max_length=100,
                unique=True
            ),
        ),
    ]