# Generated by Django 6.1.1 on 2026-09-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_payment_date'),
        ('providers', '0003_providerenrolment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='enrolment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='providers.providerenrolment'),
            preserve_default=False,
        ),
    ]
