# Generated by Django 6.1.1 on 2026-09-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerenrolment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='providerenrolment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='unpaid', max_length=20),
        ),
    ]
